
spring:
  ldap:
    urls: "ldap://35.222.32.157:389/"

demo:
  ActiveDirectory:
    domain: "almirex.dc"
    searchFilter: "(&(objectClass=user)(userPrincipalName={0})(memberof=CN=storeServices,CN=Users,DC=almirex,DC=dc))"

server:
  port: 0
